theme="dark_plus_customized"

# switch to this next release and delete the custom theme
#[theme]
#name="dark_plus"
#
#[theme.overwrite]
#"ui.virtual.inlay-hint" = {fg = "#696969" }

[keys.normal]
g = { j = "goto_next_diag", k = "goto_prev_diag" } 
"$" = ["ensure_selections_forward", "extend_to_line_end"]
"^" = ["ensure_selections_forward", "extend_to_line_start"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

[keys.normal.space.t]
s = ":toggle editor.soft-wrap"
h = ":toggle lsp.display-inlay-hints"
i = ":toggle indent-guides.render"

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"

[editor]
color-modes = true
auto-pairs = false

[editor.statusline]
left = ["mode", "file-name"]
center = ["version-control"]
right = ["diagnostics", "file-type", "spinner", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

# todo:
# 3. check in on #3791 for easy motion
# 5. watch a tutorial or something
#    a. how to really use multiple cursors
#    b. x vs X, etc
# 6. virtual line stuff
